### ISSUE TITLE
crashes when trying to control myfocuserpro2

### ISSUE THREAD

**Issue by theChef613** [SquareBoot/IPARCOS#6]
Hello!
I am trying to connect my myfucuserpro2 from [this site](https://sourceforge.net/projects/arduinoascomfocuserpro2diy/).
I am able to connect to my INDI instance which was only running myfocuserpro2 and it did recognize it. however, the focuser tab shows "unavailable" and does not seem to recognize my focuser.  I get the following crash when trying to go into settings to control the focuser. I am using API 30. any help is appreciated. thank you!!
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: marcocipriani01.iparcos, PID: 3406
    java.util.IllegalFormatPrecisionException: 102
        at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2614)
        at java.util.Formatter.parse(Formatter.java:2558)
        at java.util.Formatter.format(Formatter.java:2505)
        at java.util.Formatter.format(Formatter.java:2459)
        at org.indilib.i4j.client.INDINumberElement.getNumberAsString(INDINumberElement.java:233)
        at org.indilib.i4j.client.INDINumberElement.getValueAsString(INDINumberElement.java:214)
        at marcocipriani01.iparcos.prop.NumberPropPref.createSummary(NumberPropPref.java:57)
        at marcocipriani01.iparcos.prop.PropPref.<init>(PropPref.java:39)
        at marcocipriani01.iparcos.prop.NumberPropPref.<init>(NumberPropPref.java:38)
        at marcocipriani01.iparcos.prop.PropPref.create(PropPref.java:50)
        at marcocipriani01.iparcos.PrefsFragment.onViewCreated(PrefsFragment.java:58)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:489)
        at com.commonsware.cwac.pager.v4.ArrayPagerAdapter.finishUpdate(ArrayPagerAdapter.java:156)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:25466)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25466)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:747)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3397)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2228)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2486)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:731)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
`

**Comment by marcocipriani01** [comment]
Seems to be an INDIForJava bug (the library that communicates with INDI) but, unfortunately, its developers stopped working on it years ago. I gained their permission to take over the project and I'm trying to understand the structure of the source code before touching anything.

I'll install MyFocuserPro2 on an Arduino ASAP and let you know.

**Comment by marcocipriani01** [comment]
If you can, try setting a breakpoint on line 233, file `INDIForJava/src/main/java/org/indilib/i4j/client/INDINumberElement`:

![image](https://user-images.githubusercontent.com/20319029/103243174-43012e80-4959-11eb-871a-3417bd21fd49.png)

When the breakpoint is hit during debug, you should be able to see the value of the `numberFormat` field inside the class. A bad value there is what causes the crash.

**Comment by theChef613** [comment]
thanks again for working on this! according to their website it's not moonlite compatible. but [ardufocus ](https://www.thingiverse.com/thing:2446069)(another Arduino based focuser) is. i ran the breakpoint as requested and got the following for the numberFormat object:
result: "%.f"
count: 6
hash: 37085

I'm going to see if it's easy for me to switch from myfocuserpro2 to ardufocus easily and if so switch over. I'd really rather not resolder components if I can help it >_<

**Comment by marcocipriani01** [comment]
I think I've solved it by adding another check in the INDIForJava lib, from
```
    if (newNumberFormat.equals("%0.f")) {
        newNumberFormat = "%.0f";
    }
```
to
`if (newNumberFormat.equals("%0.f") || newNumberFormat.equals("%.f")) {  ...`

Please try it now.

By the way, if you're interested, I've developed a custom focuser similar to MyFocuserPro2 and ardufocus, [ThunderFocus](https://github.com/marcocipriani01/ThunderFocus). It's written in Java, compatible with INDI/ASCOM and IPARCOS and can work with the same circuit you have now (just change the pins in the configuration). I'm still working on the documentation but the software runs flawlessly.

**Comment by theChef613** [comment]
I quickly switched over to the ardufocus before I saw this fix, it had the same problem, but once I pulled it worked like a charm! I'll definately look into Thunderfocus. 
can't thank you enough! I'm going to keep playing around with the app and send in more reports as I find them if that's ok. 
Have you considered making this avilable via google play?

**Comment by marcocipriani01** [comment]
> can't thank you enough! I'm going to keep playing around with the app and send in more reports as I find them if that's ok.

Really appreciated! Testing the app with a different phone and INDI drivers is a must, but unfortunately I have limited hardware.

> Have you considered making this avilable via google play?

It will take some effort and I'll need to pay the Google Play fee, but I will certainly do that as soon as IPARCOS is stable and tested enough 😀

**Comment by theChef613** [comment]
confirmed working with myfocuserpro2 as well

**Comment by marcocipriani01** [comment]
Great! Meanwhile I've started working on INDIForJava and fixed the issue inside the library itself.
